apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: cmFuZ2FAb3NzZGF5a2w=
  password: TWljcm9zb2Z0QDEyMw==
  url: amRiYzpteXNxbDovL29zc2RheWtsLm15c3FsLmRhdGFiYXNlLmF6dXJlLmNvbTozMzA2L3RlYW1jP3ZlcmlmeVNlcnZlckNlcnRpZmljYXRlPXRydWUmdXNlU1NMPXRydWUmcmVxdWlyZVNTTD1mYWxzZQ==
